name: raffashe
description: "Portfólio"


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  velocity_x: ^4.2.1
  timelines: ^0.1.0
  font_awesome_flutter: ^10.7.0
  html: ^0.15.4
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/
  
  fonts:
    - family: custom
      fonts:
        - asset: assets/Poppins-Regular.ttf
        - asset: assets/Poppins-Light.ttf
          weight: 400
        - asset: assets/Poppins-Medium.ttf
          weight: 600
        - asset: assets/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/Poppins-Bold.ttf
          weight: 800
        - asset: assets/Poppins-Bold.ttf
          weight: 900      
